
services:
  app:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    ports:
      - "3978:3978"
    env_file:
      - ../backend/.env
    volumes:
      - ../data:/app/data
      - ../backend:/app/backend
